[project]
name = "eco2mix-retriever"
version = "0.1.0"
description = "eco2mix-retriever (python)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.2",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.6",
]
